#STRING FUNCTIONS

#1. LENGTH 

SELECT first_name ,LENGTH(FIRST_NAME) LEN
FROM Employee_demographics
ORDER BY LEN;

#2. UPPER, LOWER

SELECT FIRST_NAME , UPPER(FIRST_NAME) 
FROM employee_demographics;

SELECT FIRST_NAME , LOWER(FIRST_NAME) 
FROM employee_demographics;

#3. TRIM - RIGHT TRIM AND LEFT TRIM FOR leading and trailing spaces
SELECT TRIM('     KHATI    ') TM;

SELECT LTRIM('     KHATI    ') TM;

SELECT RTRIM('     KHATI    ') TM;

#LEFT,RIGTH AND SUBSTRING
SELECT BIRTH_DATE,
LEFT (BIRTH_DATE, 4) YEAR_,
RIGHT (BIRTH_DATE, 2)DATE_,
SUBSTRING(BIRTH_DATE,6,2) MONTH_
FROM employee_demographics;

#REPLACE
SELECT FIRST_NAME, REPLACE(FIRST_NAME, 'A','B') NAME_
FROM EMPLOYEE_DEMOGRAPHICS;

#LOCATE
SELECT FIRST_NAME , LOCATE('A',FIRST_NAME)
FROM employee_demographics;

#CONCAT TO COMBINE COLUMNS INTO ONE
#ADD SPACE IN INVERTED COMMAS ' ' TO HAVE SPACE BETWEEEN WORDS

SELECT FIRST_NAME, LAST_NAME,
CONCAT(FIRST_NAME,' ',LAST_NAME) FULL_NAME
FROM employee_demographics;






